### PR TITLE
Fixes after review

### LINKED ISSUE #7: Fix time zone when listing reminders
When requesting the bot to show all reminders, the reported time is not in the correct time zone

### LINKED ISSUE #8: Fix setting time zone
When asking the bot to change the user/default time zone, the time zone is reported as a city (e.g. `Athens`).
Change that so that it also supports full time zone (e.g. `Europe/Athens`), as well as make it case-insensitive (e.g. allow `athens`)

### PR DESCRIPTION
**Pull request by lykakis**
Fix #7  time zone when listing reminders
Fix #8 setting time zone

### CODE REVIEW

File: src/test/java/gr/cytech/chatreminderbot/rest/BotResourceTest.java [hunk 1]
```diff
@@ -45,15 +45,40 @@ public final void beforeEach() throws Exception {
...
+                "DisplayName","Europe/Athens", "uPWJ7AAAAAE", "1E_d3mjJGyM");
 
+        reminder.setReminderId(1);
         timerSessionBean.nextReminderDate = reminder.getWhen();
 
         botResource.timerSessionBean = timerSessionBean;
         botResource.entityManager = entityManager;
     }
+    @Test
+    public void reminderListToStirngTest(){
```
Comment (JChrist) [inline src/test/java/gr/cytech/chatreminderbot/rest/BotResourceTest.java]: typo
